-
  branches:
    only:
      - master

  configuration: Release

  image: Visual Studio 2017

  build_script:
    - cmd: dotnet restore -v m  ./src/Sprint.Filter.OData.sln
    - cmd: dotnet build  -v m -c Release ./src/Sprint.Filter.OData.sln
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts ./src/Sprint.Filter.OData/Sprint.Filter.OData.csproj
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts ./src/Sprint.Filter.OData.Mvc/Sprint.Filter.OData.Mvc.csproj
      
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: 642CQyNRZfe9fDFvEdV5ISN5ggxFvY82meXc2zwaj18sG96g4cR+sfi8xG/9enGC
      skip_symbols: false
      artifact: /.*\.nupkg/